- hosts: vpn-host
  become: yes
  gather_facts: no
  roles:
    - role: ansible_prereq

    - role: lxd_host
      lxdbr_create: yes
      lxdbr_net: "{{ vpn_container_net }}"

    - role: lxd_install_image
      container_name: "vpn-base-container"

    - role: vpn_host
