- name: Publish LXD image
  command: "lxc publish --force --alias '{{ container_name }}' '{{ container_name }}'"

- name: Export LXD image
  command: "lxc image export '{{ container_name }}' images/'{{ container_name }}'.tar.gz"
