- name: Create LXD container
  lxd_container:
    name: "{{ container_name }}"
    state: started
    source:
      type: image
      mode: pull
      server: "https://cloud-images.ubuntu.com/releases"
      protocol: "simplestreams"
      alias: "16.04"
    wait_for_ipv4_addresses: yes
